[build]
  command = "node scripts/generate-event-index.js && npm run build"
  publish = "dist"

[[functions]]
  directory = "netlify/functions"

[[scheduled]]
  name = "sync-trailers"
  path = "/.netlify/functions/sync-trailers"
  schedule = "*/15 * * * *" # Every 15 minutes