backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "events"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Main Info"
        name: "main"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "End Date (only for Steam Sale)", name: "end", widget: "datetime", required: false }
          - { label: "Event Type", name: "type", widget: "select", options: [
              { label: "Upcoming Event", value: "event" },
              { label: "Steam Sale", value: "steam_sale" },
              { label: "Old Event", value: "old_event" }
            ]
          }
      - label: "Image + Style"
        name: "visuals"
        widget: "object"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Border Color", name: "borderColor", widget: "color", required: false, default: "#ff6600" }

      - label: "Standard Links"
        name: "standard_links"
        widget: "object"
        fields:
          - label: "YouTube Link"
            name: "youtube"
            widget: "object"
            required: false
            fields:
              - { label: "URL", name: "url", widget: "string", required: false }
              - { label: "Icon", name: "icon", widget: "hidden", default: "/images/links/youtube_link.png" }

          - label: "Twitch Link"
            name: "twitch"
            widget: "object"
            required: false
            fields:
              - { label: "URL", name: "url", widget: "string", required: false }
              - { label: "Icon", name: "icon", widget: "hidden", default: "/images/links/twitch_link.png" }

          - label: "Website Link"
            name: "website"
            widget: "object"
            required: false
            fields:
              - { label: "URL", name: "url", widget: "string", required: false }
              - { label: "Icon", name: "icon", widget: "hidden", default: "/images/links/web_link.png" }

          - label: "Steam Link"
            name: "steam"
            widget: "object"
            required: false
            fields:
              - { label: "URL", name: "url", widget: "string", required: false }
              - { label: "Icon", name: "icon", widget: "hidden", default: "/images/links/steam_link.png" }

      - label: "Custom Links"
        name: "links"
        required: false
        widget: "list"
        summary: "{{fields.label}} - {{fields.url}}"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Icon Image", name: "icon", widget: "image" }
