backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "events"
    create: true
    slug: "{{slug}}"
    preview_path: "events/{{slug}}"
    identifier_field: title
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm", time_format: "HH:mm" }
      - { label: "End Date (only for Steam Sale)", name: "end", widget: "datetime", required: false, format: "YYYY-MM-DD HH:mm", time_format: "HH:mm" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Event Logo", name: "logo", widget: "image", required: false }
      - { label: "Border Color", name: "borderColor", widget: "color", required: false, default: "#ff6600" }
      - label: "Event Type"
        name: "type"
        widget: "select"
        options:
          - { label: "Upcoming Event", value: "event" }
          - { label: "Steam Sale", value: "steam_sale" }
          - { label: "Old Event", value: "old_event" }
      - label: "YouTube Link"
        name: "youtube"
        required: false
        widget: "object"
        fields:
          - { label: "URL", name: "url", widget: "string", required: false }
          - { label: "Icon", name: "icon", widget: "hidden", default: "/images/links/youtube_link.png" }
      - label: "Twitch Link"
        name: "twitch"
        required: false
        widget: "object"
        fields:
          - { label: "URL", name: "url", widget: "string", required: false }
          - { label: "Icon", name: "icon", widget: "hidden", default: "/images/links/twitch_link.png" }
      - label: "Website Link"
        name: "website"
        required: false
        widget: "object"
        fields:
          - { label: "URL", name: "url", widget: "string", required: false }
          - { label: "Icon", name: "icon", widget: "hidden", default: "/images/links/web_link.png" }
      - label: "Steam Link (Steam Sale Only)"
        name: "steam"
        required: false
        widget: "object"
        fields:
          - { label: "URL", name: "url", widget: "string", required: false, pattern: ["^https?://.*", "Must be a valid URL"], hint: "Only used if event type is Steam Sale" }
          - { label: "Icon", name: "icon", widget: "hidden", default: "/images/links/steam_link.png" }
      - label: "Custom Links"
        name: "links"
        required: false
        widget: "list"
        summary: "{{fields.label}} - {{fields.url}}"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Icon Image", name: "icon", widget: "image" }

  - name: actions
    label: Tools
    files:
      - label: Sync Trailers
        name: sync_trailers
        file: admin/sync.md
        fields:
          - label: Trigger
            name: trigger
            widget: hidden
            default: "true"
